spring:
  application:
    name: spring_security1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/spring_security1?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: create

  mustache:
    servlet:
      expose-request-attributes: true

server:
  servlet:
    session:
      timeout: 1800

